import { AlgorithmDecision, SimulationMetrics } from '../../simulation/types';
import { Cpu, CheckCircle2, ShieldCheck, Zap } from 'lucide-react';

interface AlgorithmExplainPanelProps {
  decisions: AlgorithmDecision[];
  metrics: SimulationMetrics;
}

export function AlgorithmExplainPanel({ decisions, metrics }: AlgorithmExplainPanelProps) {
  return (
    <div className="bg-white border border-black/10 rounded-2xl shadow-sm p-6 text-black">
      {/* Title */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-black/10">
        <div>
          <div className="flex items-center gap-2">
            <Cpu size={18} className="text-[#0825c6]" />
            <h3 className="font-serif text-2xl font-normal text-black">
              Underlying Optimization Engine
            </h3>
          </div>
          <p className="font-sans text-xs text-black/50 mt-1">
            Priority-weighted Critical Path Method (CPM) and Resource-Constrained Project Scheduling (RCPSP) heuristic solver.
          </p>
        </div>

        <div className="flex items-center gap-3 text-xs font-mono">
          <span className="px-3 py-1 rounded-full bg-emerald-50 text-emerald-800 border border-emerald-200 flex items-center gap-1.5">
            <Zap size={12} className="text-emerald-600" />
            Active Optimization: Online ({metrics.algorithmExecutionTimeMs}ms)
          </span>
        </div>
      </div>

      {/* Mathematical Formulation & Heuristics */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 my-6">
        {/* Objective Function Box */}
        <div className="p-4 rounded-xl border border-black/10 bg-black/[0.015]">
          <div className="text-[10px] font-sans uppercase tracking-widest text-black/50 mb-1">
            01 · Multi-Objective Loss Function
          </div>
          <div className="font-mono text-xs font-semibold text-black bg-white p-2.5 rounded-lg border border-black/10 my-2 shadow-xs">
            min J = Σ (w_f · Delay_f) + λ_gate · N_swaps + λ_idle · T_crew
          </div>
          <p className="text-[11px] font-sans text-black/60 leading-relaxed">
            Minimizes weighted passenger delays by weighting flights by priority (Emergency: 10x, VIP: 5x, Transit: 2x, Standard: 1x). Penalizes excessive gate swaps to minimize ramp towing confusion.
          </p>
        </div>

        {/* Critical Path & Task Precedence */}
        <div className="p-4 rounded-xl border border-black/10 bg-black/[0.015]">
          <div className="text-[10px] font-sans uppercase tracking-widest text-black/50 mb-1">
            02 · Directed Precedence Graph
          </div>
          <div className="font-mono text-xs font-semibold text-black bg-white p-2.5 rounded-lg border border-black/10 my-2 shadow-xs">
            Deplane → [Clean + Fuel] → Board → Pushback
          </div>
          <p className="text-[11px] font-sans text-black/60 leading-relaxed">
            Enforces strict safety and cabin flow invariants: Cabin cleaning cannot begin until deplaning finishes; Passenger boarding is locked until refuelling clears airport fire safety protocols.
          </p>
        </div>

        {/* Dynamic Resource Preemption */}
        <div className="p-4 rounded-xl border border-black/10 bg-black/[0.015]">
          <div className="text-[10px] font-sans uppercase tracking-widest text-black/50 mb-1">
            03 · Dynamic Preemption & Swap
          </div>
          <div className="font-mono text-xs font-semibold text-black bg-white p-2.5 rounded-lg border border-black/10 my-2 shadow-xs">
            ΔDelay_ripple = Max(0, T_bottleneck - Slack_adjacent)
          </div>
          <p className="text-[11px] font-sans text-black/60 leading-relaxed">
            When a disruption strikes (e.g., fuel hydrant failure or medevac inbound), idle or lower-priority resources are instantaneously reassigned, shielding critical connections.
          </p>
        </div>
      </div>

      {/* Live Algorithmic Decisions Audit Trail */}
      <div className="pt-2">
        <div className="flex items-center justify-between mb-3">
          <div className="text-xs font-sans uppercase tracking-wider text-black/70 font-semibold flex items-center gap-1.5">
            <ShieldCheck size={14} className="text-[#0825c6]" />
            <span>Real-Time Algorithmic Decision Log ({decisions.length})</span>
          </div>
          <span className="text-[10px] font-mono text-black/40">
            Auto-generated by scheduling solver
          </span>
        </div>

        <div className="space-y-2 max-h-[220px] overflow-y-auto pr-1">
          {decisions.length === 0 ? (
            <div className="text-center py-8 text-black/40 font-sans text-xs">
              No disruptions detected. System operating along nominal critical path.
            </div>
          ) : (
            decisions.map((dec) => (
              <div
                key={dec.id}
                className="p-3 rounded-xl border border-black/10 bg-black/[0.01] hover:bg-black/[0.025] transition-colors flex flex-col sm:flex-row sm:items-center justify-between gap-2"
              >
                <div className="flex items-start gap-2.5">
                  <span className="font-mono text-[11px] font-bold text-black/60 pt-0.5 whitespace-nowrap">
                    {dec.timeFormatted}
                  </span>
                  <div>
                    <div className="font-serif text-sm font-medium text-black">
                      {dec.action}
                    </div>
                    <div className="text-[11px] font-sans text-black/50">
                      Reason: {dec.reason} · <span className="text-black/70">{dec.impact}</span>
                    </div>
                  </div>
                </div>

                <div className="shrink-0 self-end sm:self-center">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-800 border border-emerald-200 font-mono text-[10px] font-bold">
                    <CheckCircle2 size={11} className="text-emerald-600" />
                    Saved {dec.savingsMinutes}m
                  </span>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
